### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by ZhenxuanSu-Sine** [RichardXue123/qqbot#1]
Write a hello world demo to show how plugins work.
Expected behavior:
- Send a message "Hello" when triggered

**Comment by RichardXue123** [comment]
Copy that.

**Comment by RichardXue123** [comment]
Dear [ZhenxuanSu-Sine],

Thank you for your inquiry about implementing a "Hello World" demo to showcase the functionality of plugins. To achieve the expected behavior of sending a "Hello" message when triggered, you may refer to the existing weather plugin as a simple use case. Here's a brief guide on how to proceed:

**Review the Weather Plugin:** Start by examining the weather plugin's code to understand how it responds to the command "/天气" with the current weather information.

**Create a New Plugin:** Develop a new plugin that will be triggered by a specific command, such as "/hello".

**Implement the Functionality:** Within the plugin's code, implement a function that sends the message "Hello" when the trigger command is received.

**Test the Plugin:** After implementation, test the plugin to ensure it behaves as expected—sending the "Hello" message upon receiving the trigger command.

**Documentation:** Don't forget to document the plugin's functionality and usage instructions for other users.

If you need further assistance or have any specific requirements, feel free to reach out. We're here to help.

Best regards,
[RichardXue]
